name: Docker

on: 
  schedule:
    - cron: '25 12 * * *'
  push: dependabot/pip/wheel-0.38.1
  branches: [ master ]
    # Publish semver tags as releases.
  tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eugeny/tabby-connection-gateway

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      
      - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
        uses: docker/setup-buildx-action@v3.0.0
        
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ghcr.io }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
         with:
         image: {{ eugeny/tabby-connection-gateway }}
         tag: |
           type=schedule
           type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
           type=semver,pattern={{version}}
           type=semver,pattern={{major}}.{{minor}}
           type=semver,pattern={{major}}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: EXTRA_DEPS=gcsfs
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger CircleCI Pipeline
      # You may pin to the exact commit or the version.
      # uses: CircleCI-Public/trigger-circleci-pipeline-action@4c19ba5233222ed6714ecfc27213e548b722301f
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0

